[pytest]
# Quy tắc tìm kiếm file chứa các bài kiểm thử
python_files = test_*.py *_test.py test.py

# Quy tắc tìm kiếm class và hàm kiểm thử
python_classes = Test*
python_functions = test_*

# Bỏ qua các thư mục không cần thiết để tăng tốc độ
norecursedirs = .git .github venv env .venv output logs
